name: Model Preview

on:
  pull_request:

jobs:
  model-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Minecraft Model Preview
        uses: smell-of-curry/mc-model-preview@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
